// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hazfit_efron
NumericVector hazfit_efron(int n, IntegerVector event, NumericVector wt_event, NumericVector wt_risk, NumericVector wt_eventrisk);
RcppExport SEXP _MachineShop_hazfit_efron(SEXP nSEXP, SEXP eventSEXP, SEXP wt_eventSEXP, SEXP wt_riskSEXP, SEXP wt_eventriskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt_event(wt_eventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt_risk(wt_riskSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt_eventrisk(wt_eventriskSEXP);
    rcpp_result_gen = Rcpp::wrap(hazfit_efron(n, event, wt_event, wt_risk, wt_eventrisk));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MachineShop_hazfit_efron", (DL_FUNC) &_MachineShop_hazfit_efron, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_MachineShop(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
