# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hazfit_efron <- function(event, wt_event, wt_risk, wt_eventrisk) {
    .Call(`_MachineShop_hazfit_efron`, event, wt_event, wt_risk, wt_eventrisk)
}

